/* global window */

// Runtime data mirrors types/runfluencer.ts and can later be replaced by Sheet/Supabase/API data.
window.RUNFLUENCER_PARTICIPANTS = [
  { id: "p001", name: "박수현", availableSlots: ["d1-night", "d2-pm"], interests: ["야경", "사진", "산책", "디저트"], activityLevel: "light", mobilityPreference: "walking", contentGoal: ["릴스", "단체사진"], groupMood: "차분하지만 사진 욕심 있는", budget: "moderate", avoid: ["너무 늦은 귀가"], note: "야경 스팟 선호" },
  { id: "p002", name: "철민", availableSlots: ["d1-night", "d2-pm"], interests: ["야경", "카지노 구경", "산책"], activityLevel: "moderate", mobilityPreference: "walking", contentGoal: ["브이로그"], groupMood: "가볍게 웃고 걷는", budget: "flexible", avoid: ["긴 대기"] },
  { id: "p003", name: "으닝", availableSlots: ["d2-pm", "d3-am"], interests: ["로컬맛집", "디저트", "카페"], activityLevel: "light", mobilityPreference: "public_transport", contentGoal: ["먹방 릴스", "스토리"], groupMood: "수다 많은", budget: "moderate", avoid: ["매운 음식"] },
  { id: "p004", name: "정채린", availableSlots: ["d1-night", "d2-pm"], interests: ["문화유산", "사진", "도시산책"], activityLevel: "moderate", mobilityPreference: "public_transport", contentGoal: ["감성사진"], groupMood: "느긋한", budget: "budget", avoid: ["복잡한 동선"] },
  { id: "p005", name: "체리핏", availableSlots: ["d2-pm", "d3-am"], interests: ["회복", "카페", "마사지"], activityLevel: "recovery", mobilityPreference: "nearby_only", contentGoal: ["휴식 사진"], groupMood: "조용하고 편한", budget: "flexible", avoid: ["강한 운동"], note: "트라이 후 회복 우선" },
  { id: "p006", name: "김신", availableSlots: ["d1-night", "d2-pm"], interests: ["로컬맛집", "야시장", "디저트"], activityLevel: "moderate", mobilityPreference: "taxi_ok", contentGoal: ["먹방 릴스"], groupMood: "활발한", budget: "moderate", avoid: ["너무 조용한 코스"] },
  { id: "p007", name: "최윤경", availableSlots: ["d2-pm"], interests: ["러닝", "릴스", "워터프런트"], activityLevel: "active", mobilityPreference: "walking", contentGoal: ["러닝 콘텐츠", "브이로그"], groupMood: "에너지 있는", budget: "budget", avoid: ["실내 위주"] },
  { id: "p008", name: "박소영", availableSlots: ["d2-pm", "d3-am"], interests: ["로컬맛집", "카페", "쇼핑"], activityLevel: "light", mobilityPreference: "public_transport", contentGoal: ["스토리"], groupMood: "편안한 수다", budget: "moderate", avoid: ["긴 오르막"] },
  { id: "p009", name: "심새날", availableSlots: ["d2-pm"], interests: ["러닝", "워킹", "릴스"], activityLevel: "active", mobilityPreference: "walking", contentGoal: ["릴스", "러닝컷"], groupMood: "빠르게 움직이는", budget: "budget", avoid: ["긴 식사"] },
  { id: "p010", name: "미나", availableSlots: ["d1-night", "d3-am"], interests: ["회복", "카페", "호텔"], activityLevel: "recovery", mobilityPreference: "nearby_only", contentGoal: ["일상 브이로그"], groupMood: "조용한", budget: "flexible", avoid: ["밤 늦은 외출"] },
  { id: "p011", name: "정다영", availableSlots: ["d1-night", "d2-pm"], interests: ["야경", "사진", "쇼핑"], activityLevel: "light", mobilityPreference: "taxi_ok", contentGoal: ["감성 릴스"], groupMood: "밝고 여유로운", budget: "flexible", avoid: ["긴 도보"] },
  { id: "p012", name: "김슬기", availableSlots: ["d2-pm"], interests: ["문화유산", "사진", "디저트"], activityLevel: "moderate", mobilityPreference: "public_transport", contentGoal: ["감성사진", "스토리"], groupMood: "차분한", budget: "moderate", avoid: ["너무 시끄러운 곳"] },
  { id: "p013", name: "김예솔", availableSlots: ["d2-pm", "d3-am"], interests: ["회복", "스파", "카페"], activityLevel: "recovery", mobilityPreference: "nearby_only", contentGoal: ["휴식 콘텐츠"], groupMood: "느긋한", budget: "flexible", avoid: ["강한 햇빛"] },
  { id: "p014", name: "백경수", availableSlots: ["d2-pm"], interests: ["러닝", "도시산책", "영상"], activityLevel: "active", mobilityPreference: "walking", contentGoal: ["브이로그", "러닝컷"], groupMood: "액티브한", budget: "moderate", avoid: ["쇼핑 위주"] },
  { id: "p015", name: "추경식", availableSlots: ["d2-pm"], interests: ["러닝", "워터프런트", "사진"], activityLevel: "active", mobilityPreference: "walking", contentGoal: ["릴스", "단체 러닝컷"], groupMood: "에너지 있는", budget: "budget", avoid: ["긴 택시 이동"] },
  { id: "p016", name: "홍지우", availableSlots: ["d1-night", "d2-pm"], interests: ["야경", "디저트", "사진"], activityLevel: "light", mobilityPreference: "walking", contentGoal: ["릴스", "인생샷"], groupMood: "밝고 가벼운", budget: "moderate", avoid: ["과한 음주"] },
  { id: "p017", name: "유지선", availableSlots: ["d2-pm"], interests: ["문화유산", "도시산책", "사진"], activityLevel: "moderate", mobilityPreference: "public_transport", contentGoal: ["사진"], groupMood: "차분한", budget: "budget", avoid: ["무리한 운동"] },
  { id: "p018", name: "원예진", availableSlots: ["d2-pm", "d3-am"], interests: ["로컬맛집", "디저트", "시장"], activityLevel: "light", mobilityPreference: "taxi_ok", contentGoal: ["먹방 릴스"], groupMood: "활발한 수다", budget: "moderate", avoid: ["긴 웨이팅"] },
  { id: "p019", name: "김효희", availableSlots: ["d2-pm", "d3-am"], interests: ["회복", "카페", "쇼핑"], activityLevel: "recovery", mobilityPreference: "nearby_only", contentGoal: ["일상 사진"], groupMood: "편안한", budget: "flexible", avoid: ["복잡한 환승"] },
  { id: "p020", name: "김은비", availableSlots: ["d1-night", "d2-pm"], interests: ["야경", "사진", "디저트"], activityLevel: "light", mobilityPreference: "walking", contentGoal: ["스토리", "릴스"], groupMood: "밝은", budget: "moderate", avoid: ["너무 먼 코스"] },
];

window.RUNFLUENCER_ROUTES = {
  cotaiNight: { id: "r-cotai-night", title: "Cotai 야경 산책", area: "Cotai Strip", duration: "70~90분", description: "스튜디오시티에서 베니션, 런더너, 윈 팰리스 방향으로 이어지는 가벼운 야경 워크.", bestFor: ["야경", "사진", "가벼운 산책"], spots: ["StudioCity", "The Londoner", "Wynn Palace Lake"], imageUrl: "https://images.unsplash.com/photo-1534008897995-27a23e859048?auto=format&fit=crop&w=900&q=80", mapPoint: { x: 68, y: 58, label: "Cotai" }, transitHint: "호텔 출발 도보 중심", bestTime: "21:30 이후" },
  taipaDessert: { id: "r-taipa-dessert", title: "Taipa 디저트 워크", area: "Taipa Village", duration: "90분", description: "에그타르트, 젤라또, 작은 골목 사진을 묶은 달콤한 저녁 코스.", bestFor: ["디저트", "사진", "수다"], spots: ["Rua do Cunha", "Pastelaria", "Taipa Houses"], imageUrl: "https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=900&q=80", mapPoint: { x: 54, y: 68, label: "Taipa" }, transitHint: "택시 10분 또는 셔틀+도보", bestTime: "오후/저녁" },
  taipaFood: { id: "r-taipa-food", title: "Taipa Village 먹거리 코스", area: "Taipa Village", duration: "2시간", description: "로컬 스낵과 디저트를 나눠 먹으며 부담 없이 움직이는 자유시간 대표 코스.", bestFor: ["로컬맛집", "먹방 릴스", "시장"], spots: ["Rua do Cunha", "Local snack shops", "Dessert cafe"], imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=900&q=80", mapPoint: { x: 52, y: 66, label: "Food" }, transitHint: "호텔에서 택시 10~15분", bestTime: "12:30~15:00" },
  senadoSnack: { id: "r-senado-snack", title: "Senado Square 로컬 스낵 코스", area: "Macau Peninsula", duration: "2~2.5시간", description: "세나도 광장 주변의 포르투갈식 골목과 로컬 간식을 함께 즐기는 코스.", bestFor: ["로컬맛집", "문화유산", "사진"], spots: ["Senado Square", "St. Dominic's", "Local bakery"], imageUrl: "https://images.unsplash.com/photo-1519677100203-a0e668c92439?auto=format&fit=crop&w=900&q=80", mapPoint: { x: 36, y: 30, label: "Senado" }, transitHint: "택시 20~25분", bestTime: "13:00~17:00" },
  resortCafe: { id: "r-resort-cafe", title: "리조트 카페 휴식", area: "Cotai Resort Zone", duration: "60~90분", description: "트라이 세션 이후 이동을 줄이고 시원한 실내에서 회복하는 카페 코스.", bestFor: ["회복", "카페", "호텔"], spots: ["StudioCity Cafe", "Cotai indoor mall", "Hotel lounge"], imageUrl: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=900&q=80", mapPoint: { x: 70, y: 62, label: "Cafe" }, transitHint: "호텔/리조트 안쪽", bestTime: "언제든" },
  lightSpa: { id: "r-light-spa", title: "가벼운 스파·마사지 코스", area: "Cotai / Hotel nearby", duration: "90~120분", description: "무리한 이동 없이 다리 피로를 풀고 저녁 일정을 가볍게 이어가는 회복 코스.", bestFor: ["마사지", "스파", "회복"], spots: ["Hotel spa", "Foot massage", "Quiet cafe"], imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=900&q=80", mapPoint: { x: 73, y: 60, label: "Spa" }, transitHint: "예약 가능 여부 확인", bestTime: "오후 회복 타임" },
  cotaiMorning: { id: "r-cotai-morning", title: "Cotai morning walk", area: "Cotai Strip", duration: "50~70분", description: "복잡해지기 전 코타이 주변을 걷고 러닝/워킹 콘텐츠를 남기는 코스.", bestFor: ["러닝", "릴스", "브이로그"], spots: ["StudioCity front", "Cotai Strip", "The Parisian view"], imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80", mapPoint: { x: 66, y: 56, label: "Walk" }, transitHint: "도보 순환", bestTime: "오전 또는 16:00 이후" },
  waterfrontRun: { id: "r-waterfront-run", title: "Waterfront running content route", area: "Taipa Waterfront", duration: "70~100분", description: "평지 위주의 워터프런트에서 짧은 러닝 컷, 워킹 컷, 단체 릴스를 찍는 코스.", bestFor: ["러닝 콘텐츠", "워터프런트", "영상"], spots: ["Taipa Waterfront", "Bridge view", "Sunset point"], imageUrl: "https://images.unsplash.com/photo-1502904550040-7534597429ae?auto=format&fit=crop&w=900&q=80", mapPoint: { x: 48, y: 54, label: "Run" }, transitHint: "택시 10분 후 러닝", bestTime: "16:30~18:00" },
  ruinsPhoto: { id: "r-ruins-photo", title: "Ruins of St. Paul’s 포토 워크", area: "Historic Centre", duration: "2시간", description: "성 바울 성당 유적과 주변 계단, 골목을 따라 감성 사진을 찍는 코스.", bestFor: ["문화유산", "감성사진", "도시산책"], spots: ["Ruins of St. Paul's", "Monte Fort", "Historic alleys"], imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=900&q=80", mapPoint: { x: 32, y: 24, label: "Ruins" }, transitHint: "택시 25분", bestTime: "15:00 이후" },
  senadoPhoto: { id: "r-senado-photo", title: "Senado Square photo walk", area: "Senado Square", duration: "90~120분", description: "물결무늬 광장과 파스텔 톤 건물을 배경으로 걷는 도심 포토 코스.", bestFor: ["사진", "문화유산", "카페"], spots: ["Senado Square", "Leal Senado", "Portuguese alleys"], imageUrl: "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=900&q=80", mapPoint: { x: 36, y: 32, label: "Photo" }, transitHint: "택시 20~25분", bestTime: "오후" },
  hacSaBeach: { id: "r-hacsa-beach", title: "Hac Sa Beach 쿨다운", area: "Coloane", duration: "2~2.5시간", description: "바다 앞에서 걷고 쉬는 회복형 코스. 촬영 욕심보다 컨디션 회복에 좋습니다.", bestFor: ["바다", "회복", "사진"], spots: ["Hac Sa Beach", "Beach cafe", "Coloane coast"], imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80", mapPoint: { x: 62, y: 88, label: "Beach" }, transitHint: "택시 20분 내외", bestTime: "오전/해질녘" },
  coloaneVillage: { id: "r-coloane-village", title: "Coloane Village 로컬 워크", area: "Coloane", duration: "2시간", description: "한적한 마을길, 에그타르트, 바다 앞 사진을 묶은 느긋한 코스.", bestFor: ["로컬", "디저트", "사진"], spots: ["Coloane Village", "Lord Stow's", "Chapel square"], imageUrl: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80", mapPoint: { x: 54, y: 84, label: "Coloane" }, transitHint: "택시 18~22분", bestTime: "오후" },
  teamShopping: { id: "r-team-shopping", title: "Cotai Gallery 쇼핑 루프", area: "Cotai Resort Zone", duration: "60~120분", description: "더위와 피로를 피하면서 기념품, 운동복, 카페를 한 번에 처리하는 실내 코스.", bestFor: ["쇼핑", "카페", "근거리"], spots: ["The Londoner", "Venetian shops", "Cotai cafe"], imageUrl: "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?auto=format&fit=crop&w=900&q=80", mapPoint: { x: 69, y: 55, label: "Shop" }, transitHint: "실내 도보", bestTime: "더운 시간대" },
  nightFountain: { id: "r-night-fountain", title: "Wynn Palace 분수 포토 스팟", area: "Cotai Strip", duration: "45~70분", description: "짧게 강한 야경 컷을 뽑기 좋은 코스. Day 1 밤에 부담 없이 붙이기 좋습니다.", bestFor: ["야경", "릴스", "짧은 코스"], spots: ["Wynn Palace", "Performance Lake", "Cotai lights"], imageUrl: "https://images.unsplash.com/photo-1518623489648-a173ef7824f3?auto=format&fit=crop&w=900&q=80", mapPoint: { x: 76, y: 58, label: "Lights" }, transitHint: "도보/택시 짧게", bestTime: "21:30 이후" },
};

window.RUNFLUENCER_ROUTE_LIBRARY = Object.values(window.RUNFLUENCER_ROUTES);

const P = window.RUNFLUENCER_PARTICIPANTS;
const R = window.RUNFLUENCER_ROUTES;

window.RUNFLUENCER_FREE_TIME_SLOTS = [
  { id: "d1-night", label: "DAY 1 · 21:30 ~", title: "디너 후 야간 자유시간", date: "2026-06-26", description: "코타이 야경, 가벼운 산책, 호텔 근처 짧은 코스 중심" },
  { id: "d2-pm", label: "DAY 2 · 11:30 ~", title: "트라이 세션 이후 오후 자유시간", date: "2026-06-27", description: "가장 긴 자유시간. 맛집, 문화유산, 회복, 콘텐츠 촬영을 슬롯별로 분산" },
  { id: "d3-am", label: "DAY 3 · 09:00 ~", title: "체크아웃 전 오전 자유시간", date: "2026-06-28", description: "짧고 안전한 근거리 회복, 카페, 마지막 디저트 코스 중심" },
];

window.RUNFLUENCER_MATCHED_GROUPS = [
  { id: "d1-night-view", slotId: "d1-night", name: "Night View & Chill Team", concept: "야경, 사진, 가벼운 산책", members: [P[0], P[1], P[15], P[19]], matchScore: 94, matchReasons: ["Day 1 야간 가능 시간이 일치해요.", "야경·사진·디저트 선호가 뚜렷하게 맞아요.", "도보 중심 코스라 디너 후 부담이 낮아요."], tags: ["야경", "사진", "가벼운 산책", "릴스"], recommendedRoutes: [R.cotaiNight, R.taipaDessert], meetingSuggestion: "Day 1 21:40 · StudioCity 로비", cautions: ["야간 이동은 2명 이상 함께 움직이기", "사진 촬영 후 호텔 복귀 시간을 먼저 정하기"], kakaoMessage: "" },
  { id: "d1-hotel-easy", slotId: "d1-night", name: "Hotel Easy Night Team", concept: "호텔 근처, 짧은 이동, 컨디션 관리", members: [P[3], P[5], P[9], P[10]], matchScore: 86, matchReasons: ["밤 늦은 긴 이동을 피해야 하는 멤버가 섞여 있어요.", "사진·야시장·휴식 니즈를 호텔 근처 코스로 절충할 수 있어요.", "택시 가능 멤버가 있어 컨디션에 따라 동선을 조정하기 쉬워요."], tags: ["근거리", "야시장", "호텔", "사진"], recommendedRoutes: [R.resortCafe, R.cotaiNight], meetingSuggestion: "Day 1 21:35 · 엘리베이터 홀", cautions: ["컨디션이 낮으면 호텔 카페 코스로 축소", "야시장 이동 시 택시 복귀 기준 시간을 정하기"], kakaoMessage: "" },

  { id: "d2-foodie", slotId: "d2-pm", name: "Local Foodie Team", concept: "로컬 맛집, 디저트, 수다", members: [P[2], P[5], P[7], P[17], P[19]], matchScore: 91, matchReasons: ["로컬맛집과 디저트 관심사가 강하게 겹쳐요.", "먹방 릴스와 스토리 콘텐츠 목표가 잘 맞아요.", "대중교통 또는 택시 이동에 열려 있어 선택지가 넓어요."], tags: ["로컬맛집", "디저트", "먹방 릴스", "수다"], recommendedRoutes: [R.taipaFood, R.senadoSnack], meetingSuggestion: "Day 2 12:20 · 호텔 로비", cautions: ["웨이팅이 길면 바로 2순위 가게로 전환", "매운 음식 옵션은 주문 전 확인"], kakaoMessage: "" },
  { id: "d2-recovery", slotId: "d2-pm", name: "Recovery & Cafe Team", concept: "운동 후 회복, 카페, 마사지", members: [P[4], P[10], P[12], P[18]], matchScore: 89, matchReasons: ["트라이 이후 피로도를 낮게 가져가려는 니즈가 맞아요.", "근거리 이동과 실내 휴식 선호가 강해요.", "예산이 비교적 유연해 카페·스파 옵션을 선택하기 좋아요."], tags: ["회복", "카페", "마사지", "근거리"], recommendedRoutes: [R.resortCafe, R.lightSpa], meetingSuggestion: "Day 2 12:00 · StudioCity 카페 앞", cautions: ["마사지 예약 가능 여부를 먼저 확인", "컨디션이 낮으면 카페 코스만 진행"], kakaoMessage: "" },
  { id: "d2-runner", slotId: "d2-pm", name: "Runner Content Team", concept: "러닝/워킹, 릴스, 브이로그", members: [P[6], P[8], P[13], P[14], P[0]], matchScore: 93, matchReasons: ["운동 강도 active 멤버 중심이라 페이스 충돌이 적어요.", "러닝컷·릴스·브이로그 목표가 명확히 겹쳐요.", "도보 이동 선호가 같아 짧은 콘텐츠 루트를 만들기 좋아요."], tags: ["러닝", "릴스", "워터프런트", "브이로그"], recommendedRoutes: [R.cotaiMorning, R.waterfrontRun], meetingSuggestion: "Day 2 16:30 · 호텔 정문", cautions: ["수분 보충 필수", "무리한 페이스보다 촬영 구간 중심으로 진행"], kakaoMessage: "" },
  { id: "d2-culture", slotId: "d2-pm", name: "Culture Photo Team", concept: "문화유산, 감성 사진, 도시 산책", members: [P[3], P[11], P[16], P[1], P[15]], matchScore: 87, matchReasons: ["문화유산·감성사진·도시산책 선호가 잘 맞아요.", "대중교통 또는 도보 이동 선호라 반도 쪽 이동 계획을 세우기 쉬워요.", "차분한 포토 워크와 야경·디저트 니즈를 함께 담을 수 있어요."], tags: ["문화유산", "감성사진", "도시산책"], recommendedRoutes: [R.ruinsPhoto, R.senadoPhoto], meetingSuggestion: "Day 2 12:30 · 호텔 로비", cautions: ["햇빛이 강하면 실내 카페 휴식 포함", "성 바울 주변 혼잡 시간대에는 소지품 주의"], kakaoMessage: "" },

  { id: "d3-recovery-cafe", slotId: "d3-am", name: "Checkout Cafe Team", concept: "체크아웃 전 카페, 회복, 짧은 쇼핑", members: [P[4], P[9], P[12], P[18]], matchScore: 92, matchReasons: ["Day 3 오전 가능 시간이 겹치고 근거리 선호가 강해요.", "회복·카페·호텔 주변 관심사가 잘 맞아요.", "체크아웃 전 짐 보관과 복귀 시간을 관리하기 쉬워요."], tags: ["오전", "회복", "카페", "근거리"], recommendedRoutes: [R.resortCafe, R.lightSpa], meetingSuggestion: "Day 3 09:20 · 짐 보관 후 로비", cautions: ["11:30 로비 집결 시간을 넘기지 않기", "마사지 코스는 짧은 옵션만 선택"], kakaoMessage: "" },
  { id: "d3-dessert-walk", slotId: "d3-am", name: "Last Bite Walk Team", concept: "마지막 디저트, 가벼운 산책, 짧은 콘텐츠", members: [P[2], P[7], P[17]], matchScore: 88, matchReasons: ["디저트·로컬 스낵 선호가 겹쳐요.", "오전 짧은 일정에 맞춰 Taipa 중심으로 끝낼 수 있어요.", "먹방 릴스와 스토리 콘텐츠 목표가 잘 맞아요."], tags: ["디저트", "마지막 쇼핑", "스토리"], recommendedRoutes: [R.taipaDessert, R.taipaFood], meetingSuggestion: "Day 3 09:15 · 호텔 로비", cautions: ["체크아웃을 먼저 마치고 출발", "웨이팅이 생기면 포장 위주로 전환"], kakaoMessage: "" },
];

window.RUNFLUENCER_MATCHED_GROUPS.forEach(group => {
  const slot = window.RUNFLUENCER_FREE_TIME_SLOTS.find(item => item.id === group.slotId);
  group.kakaoMessage = [
    `[마카오 자유일정 매칭] ${slot ? slot.label : group.slotId}`,
    `${group.name}`,
    `콘셉트: ${group.concept}`,
    `멤버: ${group.members.map(member => member.name).join(", ")}`,
    `추천 만남: ${group.meetingSuggestion}`,
    `추천 코스 1: ${group.recommendedRoutes[0].title} (${group.recommendedRoutes[0].duration})`,
    `추천 코스 2: ${group.recommendedRoutes[1].title} (${group.recommendedRoutes[1].duration})`,
    `주의: ${group.cautions.join(" / ")}`,
    "추천 결과는 참고용이라 현장에서 편하게 조정해도 됩니다.",
  ].join("\n");
});
